OriginalApplication/book_review/config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :inquiry, only: [:new, :create]
  resources :books, only: [:index] do
    collection do
      get 'search'
    end

    resources :user_reviews, only: [:show]
  end
end

OriginalApplication/book_review/app/models/book.rb
class Book < ApplicationRecord
  has_many :user_reviews
end

OriginalApplication/book_review/app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

OriginalApplication/book_review/app/models/user_review.rb
class UserReview < ApplicationRecord
  belongs_to :book
end

OriginalApplication/book_review/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def search
    @books = Book.where('title LIKE(?)', "%#{params_search_keyword}%")
  end

  private
  def params_search_keyword
    params[:search_keyword]
  end
end

OriginalApplication/book_review/app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    Inquiry.create(inquiry_params)
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:email, :user_name, :target_url, :inquiry_text)
  end
end

OriginalApplication/book_review/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @user_reviews = UserReview.all.limit(6)
  end
end

OriginalApplication/book_review/app/controllers/user_review_controller.rb
class UserReviewController < ApplicationController
  def show
    @user_review = UserReview.find(params[:id])
  end
end

OriginalApplication/book_review/app/controllers/user_reviews_controller.rb
class UserReviewsController < ApplicationController
  def show
    @user_review = UserReview.find(params[:id])
  end
end

OriginalApplication/book_review/app/helpers/application_helper.rb
module ApplicationHelper
  def copyright
    text = 'Copyright (c) 2018'
    if Date.today.year > 2018
      text << '-' + Date.today.year.to_s
    end
    text << ' project_j , All Rights Reserved.'
    text
  end
end

OriginalApplication/book_review/app/helpers/books_helper.rb
module BooksHelper
end

OriginalApplication/book_review/app/helpers/inquiry_helper.rb
module InquiryHelper
end

OriginalApplication/book_review/app/helpers/top_helper.rb
module TopHelper
end

OriginalApplication/book_review/app/helpers/user_review_helper.rb
module UserReviewHelper
end

OriginalApplication/book_review/app/views/top/_user_review_card.html.erb
<div class="review_card">
  <div>
    <h3 class="book_title">Title: <%= user_review.book.title %></h3>
  </div>
  <div class="user_review">
    <div class="book_visual">
      <%= image_tag("01_readablecode.jpg", size: "120x160") %>
    </div>
    <div class="user_review_text">
      <%= user_review.review_text %>
    </div>
  </div>
  <div class="review_link">
    <ul><li><%= link_to('レビューの全文を見る', book_user_review_path(book_id: user_review.book.id, id: user_review.id)) %></li></ul>
  </div>
</div>

OriginalApplication/book_review/app/views/top/index.html.erb
<div class="index_container">
  <div class="content">
    <div class="catch">
      <h1 class="catch_phrase">出会えなかった筈の物語が、此処にある</h1>
    </div>
  </div>
  <div class="content">
    <div class="pickup">
      <h2>Pickup phrase</h2>
      <p>
        親譲りの無鉄砲で小供の時から損ばかりしている。小学校に居る時分学校の二階から飛び降りて一週間ほど腰を抜かした事がある。なぜそんな無闇をしたと聞く人があるかも知れぬ。別段深い理由でもない。新築の二階から首を出していたら、同級生の一人が冗談に、いくら威張っても、そこから飛び降りる事は出来まい。弱虫やーい。と囃したからである。小使に負ぶさって帰って来た時、おやじが大きな眼をして二階ぐらいから飛び降りて腰を抜かす奴があるかと云ったから、この次は抜かさずに飛んで見せますと答えた。（青空文庫より）
      <p>
    </div>
  </div>
  <div class="content">
    <div class="content_detail">
      <h2>レビュー</h2>
      <!--ここにrender partial: reviewsを入れる-->
      <% @user_reviews.each do |user_review| %>
        <%= render partial: 'user_review_card', locals: { user_review: user_review } %>
      <% end %>
    </div>
  </div>
</div>