AdvancedCurriculum/profy/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "top#index"
  resources :users, only: [:show, :edit, :update]
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only: [:create, :show]
  resources :answers, only: [:new, :create, :edit, :update]
end

AdvancedCurriculum/profy/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_one :feed_content, as: :content, dependent: :destroy

  #callback
  after_create :create_feed_content
  after_update :update_feed_content

  #validation
  validates_presence_of :user_id, :text

  private

  def create_feed_content
    self.feed_content = FeedContent.create(group_id: question.group_id, updated_at: updated_at)
  end

  def update_feed_content
    self.feed_content.update(updated_at: updated_at)
  end
end

AdvancedCurriculum/profy/app/models/feed_content.rb
class FeedContent < ActiveRecord::Base
  belongs_to :content, polymorphic: true
end

AdvancedCurriculum/profy/app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_many :questions, -> { order("created_at DESC") }
  has_many :feed_contents, -> { order("updated_at DESC") }
end

AdvancedCurriculum/profy/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  has_many :answers
  has_one :feed_content, as: :content, dependent: :destroy

  validates_presence_of :user_id, :text, :group_id

  #callback
  after_create :create_feed_content

  def user_answer(user_id)
    Answer.find_by(user_id: user_id, question_id: id)
  end

  def answered?(user)
    answers.exists?(user_id: user.id)
  end

  private

  def create_feed_content
    self.feed_content = FeedContent.create(group_id: group_id, updated_at: updated_at)
  end
end

AdvancedCurriculum/profy/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :group_key

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         authentication_keys: [:email, :group_key]

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]

  belongs_to :group
  has_many :questions, -> { order("created_at DESC") }
  has_many :answers, -> { order("updated_at DESC") }
  has_many :answered_questions, through: :answers, source: :question

  #validation
  before_validation :group_key_to_id, if: :has_group_key?

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    group_key = conditions.delete(:group_key)
    group_id = Group.where(key: group_key).first
    email = conditions.delete(:email)

    # devise認証を、複数項目に対応させる
    if group_id && email
      where(conditions).where(["group_id = :group_id AND email = :email",
                               { group_id: group_id, email: email }]).first
    elsif conditions.has_key?(:confirmation_token)
      where(conditions).first
    else
      false
    end
  end

  def name
    "#{family_name} #{first_name}"
  end

  def name_kana
    "#{family_name_kana} #{first_name_kana}"
  end

  def full_profile?
    avatar? && family_name? && first_name? && family_name_kana? && first_name_kana?
  end

  private
  def has_group_key?
    group_key.present?
  end

  def group_key_to_id
    group = Group.where(key: group_key).first_or_create
    self.group_id = group.id
  end
end

AdvancedCurriculum/profy/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :redirect, only: :new

  def new
    @question = Question.find(params[:question_id])
    @answer = Answer.new
    @answer.question_id = @question.id
  end

  def create
    @answer = Answer.create(create_params)
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def update
    @answer = Answer.find(params[:id])
    @question = @answer.question
    @answer.update(update_params)
  end

  private

  def create_params
    params.require(:answer).permit(:question_id, :text).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:answer).permit(:text)
  end

  def redirect
    if Answer.exists?(question_id: params[:question_id], user_id: current_user.id)
      redirect_to :root
    end
  end
end

AdvancedCurriculum/profy/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # sign_inのときに、group_keyも許可する
    devise_parameter_sanitizer.permit(:sign_in, keys:[:group_key])
    # sign_upのときに、group_keyも許可する
    devise_parameter_sanitizer.permit(:sign_up, keys:[:group_key])
    #account_updateのときに、group_keyも許可する
    devise_parameter_sanitizer.permit(:account_update, keys:[:group_key])
  end
end

AdvancedCurriculum/profy/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(update_params)
  end

  private

  def update_params
    params.require(:group).permit(:key, :detail)
  end
end

AdvancedCurriculum/profy/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    Question.create(create_params)
    redirect_to :root and return
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end

  private

  def create_params
    params.require(:question).permit(:text).merge(user_id: current_user.id, group_id: current_user.group_id)
  end
end

AdvancedCurriculum/profy/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @question = Question.new
    @feed_contents = current_user.group.feed_contents.includes(:content).page(params[:page]).per(5)
    @feed_contents_resource = @feed_contents.map(&:content)
  end
end

AdvancedCurriculum/profy/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @questions = @user.answered_questions.uniq
  end

  def edit
  end

  def update
    current_user.update(update_params)
  end

  private

  def update_params
    params.require(:user).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :avatar)
  end
end

AdvancedCurriculum/profy/app/helpers/answers_helper.rb
module AnswersHelper
end

AdvancedCurriculum/profy/app/helpers/groups_helper.rb
module GroupsHelper
end

AdvancedCurriculum/profy/app/helpers/questions_helper.rb
module QuestionsHelper
end

AdvancedCurriculum/profy/app/helpers/users_helper.rb
module UsersHelper
end

AdvancedCurriculum/profy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
  <meta name='viewport' content='width=device-width, initial-scale=1.0'>
  <title>Profy<%= yield :title %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
<script type='text/javascript' charset='utf-8'>
  $(function(){
    $.material.init();
  });
</script>
<%= render partial: 'common/header' %>
<div class='container'>
  <div class='row'>
    <div class='col-lg-12'>
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
  <footer class='row text-center'>
    <p>(C) Profy 2015</p>
  </footer>
</div>
</body>
</html>

AdvancedCurriculum/profy/app/views/top/index.html.erb
<% unless current_user.full_profile? %>
  <header class="header_top panel panel-default col-lg-12 no-profile">
    <h2>まずは、あなたの基本プロフィールを登録しましょう！</h2>
    <p>Profyは友達の質問に答えながらプロフィールを作るサービスです！</p>
    <%= link_to "プロフィールを登録する", edit_user_path(current_user), { class: "btn btn-lg btn-primary withripple" } %>
  </header>
<% else %>
  <div class="posting_form top_content">
    <header class="posting_header">
      <div class="posting_image icon_image" style="background-image: url(<%= current_user.avatar.url(:medium) %>);"></div>
      <div class="posting_user_info user_info">
        <%= current_user.name %>
      </div>
    </header>
    <%= form_for(@question) do |f| %>
      <%= f.text_field :text, placeholder: "例：好きな食べ物は？" %>
      <%= f.submit "質問する" %>
    <% end %>
  </div>

  <%= render @feed_contents_resource %>
  <%= paginate(@feed_contents)%>
<% end %>

AdvancedCurriculum/profy/app/views/users/_question.html.erb
<div class="question_content top_content">
  <div class="question_body">
    <div class="question_box">
      <span class="q">Q</span>
      <span class="question_text"><%= question.text %></span>
    </div>
    <div class="answer_box" style="margin-bottom: 10px;">
      <span class="a">A</span>
      <span class="answer_text"><%= question.user_answer(@user.id).text %></span>
      <% if @user.id == current_user.id %>
      <small class="edit">
        <%= link_to '編集', edit_answer_path(question.user_answer(@user.id)) %>
      </small>
      <% end %>
    </div>
  </div>
</div>

AdvancedCurriculum/profy/app/views/users/edit.html.erb
<% provide :title, " | プロフィール編集" %>
<div class="row form">
  <div class="col-lg-12">
    <%= form_for current_user do |f| %>
      <h2>プロフィール画像</h2>
      <div class="form-group file">
        <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
      </div>
      <h2>登録情報</h2>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name, placeholder: "姓", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          <%= f.text_field :first_name, placeholder: "名", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-lg-6">
          <%= f.text_field :family_name_kana, placeholder: "セイ", class: "form-control" %>
        </div>
        <div class="col-lg-6">
          <%= f.text_field :first_name_kana, placeholder: "メイ", class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.submit "送信", class: "btn btn-primary withripple" %>
      </div>
    <% end %>
  </div>
</div>

AdvancedCurriculum/profy/app/views/users/show.html.erb
<% provide :title, " | #{@user.name}さん" %>
<div class="row form user_profile">
  <div class="col-lg-12">
    <div class="image" style="background-image: url(<%= @user.avatar.url(:medium) %>);"></div>
    <h2><%= @user.name %><span><%= @user.name_kana %></span></h2>
    <% if current_user.id == @user.id %>
    <div class="profile_edit">
      <%= link_to 'プロフィール編集', edit_user_path(current_user), {:class => 'btn btn-primary withripple' }%>
    </div>
    <% end %>
    <% if @questions.present? %>
      <h3>このユーザーの回答した質問</h3>
      <div class='clearfix'>
        <%= render partial: 'users/question', collection: @questions %>
      </div>
    <% end %>
  </div>
</div>

AdvancedCurriculum/profy/app/views/users/update.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3>プロフィールの編集が完了しました。</h3>
    <%= link_to "ホームに戻る", root_path %>
  </div>
</div>